Jacqueline development
Jacquelinet19/software-product-sprint pull request #1
Opened 2021-02-26 03:34 UTC by Jacquelinet19

2021-02-26 18:30 UTC, Jacquelinet19 commented
First set of changes for week 1

2021-03-03 04:00 UTC, emilyzhang242 requested changes
Good job overall! Just some small comments regarding CSS

2021-03-03 04:00 UTC, emilyzhang242 commented on portfolio/src/main/webapp/index.html
> +      <a href="https://www.linkedin.com/in/jacqueline-tapia-423574197/">LinkedIn</a>  <a href="https://github.com/Jacquelinet19">GitHub</a>
Please move the second <a> tag down to its own line.

2021-03-03 04:00 UTC, emilyzhang242 commented on portfolio/src/main/webapp/index.html
> +       <img src="/images/profilepic.jpg" style="width:300px;height:400x;"/>
Please add the style here into a separate CSS file. Inline CSS makes it harder to maintain sites, especially when collaborating with others.

2021-03-03 04:00 UTC, emilyzhang242 commented on portfolio/src/main/webapp/index.html
> +       <img src="/images/profilepic.jpg" style="width:300px;height:400x;"/>
It might be nice to add an "alt" tag for the image, just in case users have slow connections or other issues with images loading. This is also important for accessibility because visually impaired users won't know what the image is showing.

2021-03-09 20:48 UTC, emilyzhang242 approved these changes
Other than one super small nitpick, looks great!

2021-03-09 20:48 UTC, emilyzhang242 commented on portfolio/src/main/java/com/google/sps/servlets/HelloWorldServlet.java
> +
Nit: please remove this extra space

2021-04-01 01:43 UTC, merged